// Generated by Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import Foundation;
@import ObjectiveC;
@import CoreGraphics;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class MonthYearPickerView;
@class UILabel;
@class UIView;
@class Spinner;
@class UITextField;
@class UIBarButtonItem;
@class BrowserParams;
@class UIButton;
@class UIImageView;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC9Instamojo12CardFormView")
@interface CardFormView : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified payButton;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified cvvTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified expiryDateTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified nameTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified cardNumberTextField;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified cardImageView;
@property (nonatomic, strong) IBOutlet MonthYearPickerView * _Null_unspecified expiryPickerView;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified cardNumberErrorLable;
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified cardNumberDivider;
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified nameDivider;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified nameErrorLable;
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified expiryDateDivider;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified expiryDateErrorLable;
@property (nonatomic, strong) IBOutlet UIView * _Null_unspecified cvvDivider;
@property (nonatomic, strong) IBOutlet UILabel * _Null_unspecified cvvErrorLable;
@property (nonatomic) NSInteger cardType;
@property (nonatomic) float amountToBePayed;
@property (nonatomic, strong) Spinner * _Null_unspecified spinner;
@property (nonatomic, strong) UITextField * _Null_unspecified textField;
@property (nonatomic) BOOL invalidEntries;
- (void)viewDidLoad;
- (void)doneButton_ClickedWithSender:(UIBarButtonItem * _Nonnull)sender;
- (void)prepareCheckOut;
- (void)validateEntries;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField;
- (void)initUI SWIFT_METHOD_FAMILY(none);
- (BOOL)cardNumberDidChangeWithRange:(NSRange)range;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string;
- (void)onFinishWithParams:(BrowserParams * _Nonnull)params error:(NSString * _Nonnull)error;
- (IBAction)checkout:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDictionary;
@class UITableView;
@class UITableViewCell;

SWIFT_CLASS("_TtC9Instamojo14EMIOptionsView")
@interface EMIOptionsView : UIViewController <UITableViewDelegate, UITableViewDataSource>
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified emiOptionsTableView;
@property (nonatomic, strong) NSDictionary * _Nonnull values;
- (void)viewDidLoad;
- (void)loadOptions;
- (double)getEMIAmountWithTotalAmount:(NSString * _Nonnull)totalAmount interest:(NSInteger)interest tenure:(NSInteger)tenure;
- (NSString * _Nonnull)getFinalAmountWithAmount:(double)amount;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9Instamojo9Instamojo")
@interface Instamojo : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL instance;)
+ (BOOL)instance;
+ (void)setInstance:(BOOL)value;
/**
  Sets the base url for all network calls
  @param baseUrl URl
*/
+ (void)initialize SWIFT_METHOD_FAMILY(none);
+ (void)setLogLevelWithLevel:(BOOL)level;
/**
  Sets the base url for all network calls
  @param baseUrl URl
*/
+ (void)setBaseUrlWithUrl:(NSString * _Nonnull)url;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIStoryboard;
@class UISearchController;

SWIFT_CLASS("_TtC9Instamojo15ListOptionsView")
@interface ListOptionsView : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchResultsUpdating>
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified banksTableView;
@property (nonatomic, copy) NSString * _Null_unspecified paymentOption;
@property (nonatomic, strong) UIStoryboard * _Nonnull mainStoryboard;
@property (nonatomic, copy) NSString * _Null_unspecified submissionURL;
@property (nonatomic, strong) UISearchController * _Nonnull resultSearchController;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)startJuspayBrowserWithParams:(BrowserParams * _Nonnull)params;
- (void)setOptions;
- (void)viewWillDisappear:(BOOL)animated;
- (void)updateSearchResultsForSearchController:(UISearchController * _Nonnull)searchController;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9Instamojo19MonthYearPickerView")
@interface MonthYearPickerView : UIPickerView <UIPickerViewDelegate, UIPickerViewDataSource>
@property (nonatomic, copy) NSArray<NSString *> * _Null_unspecified months;
@property (nonatomic, copy) NSArray<NSNumber *> * _Null_unspecified years;
@property (nonatomic) NSInteger month;
@property (nonatomic) NSInteger year;
@property (nonatomic, copy) void (^ _Nullable onDateSelected)(NSInteger, NSInteger);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)commonSetup;
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
@end


@interface NSMutableURLRequest (SWIFT_EXTENSION(Instamojo))
- (void)setBodyContentWithParameters:(NSDictionary<NSString *, id> * _Nonnull)parameters;
@end

@class NSMutableArray;

SWIFT_CLASS("_TtC9Instamojo18PaymentOptionsView")
@interface PaymentOptionsView : UIViewController <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified paymentOptionsTableView;
@property (nonatomic, strong) NSMutableArray * _Nonnull paymentOptions;
@property (nonatomic, strong) UIStoryboard * _Nonnull mainStoryboard;
- (void)viewDidLoad;
- (void)reloadDataBasedOnOrder;
- (void)didReceiveMemoryWarning;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)onNetBankingSelectedWithOptions:(NSString * _Nonnull)options;
- (void)viewDidAppear:(BOOL)animated;
- (void)onCreditCardSelected;
- (void)onDebitCardSelected;
- (void)onEmiSelectedWithOptions:(NSString * _Nonnull)options;
- (void)onWalletSelectedWithOptions:(NSString * _Nonnull)options;
- (void)onUPISelected;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class JuspaySafeBrowser;

SWIFT_CLASS("_TtC9Instamojo21PaymentViewController")
@interface PaymentViewController : UIViewController
@property (nonatomic, strong) JuspaySafeBrowser * _Nonnull juspaySafeBrowser;
@property (nonatomic, strong) BrowserParams * _Null_unspecified params;
@property (nonatomic) BOOL cancelled;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (BOOL)navigationShouldPopOnBackButton;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIActivityIndicatorView;
@class UIBlurEffect;
@class UIVisualEffect;

SWIFT_CLASS("_TtC9Instamojo7Spinner")
@interface Spinner : UIVisualEffectView
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, readonly, strong) UIView * _Nonnull background;
@property (nonatomic, readonly, strong) UIActivityIndicatorView * _Nonnull activityIndictor;
@property (nonatomic, readonly, strong) UILabel * _Nonnull label;
@property (nonatomic, readonly, strong) UIBlurEffect * _Nonnull blurEffect;
@property (nonatomic, readonly, strong) UIVisualEffectView * _Nonnull vibrancyView;
- (nonnull instancetype)initWithText:(NSString * _Nonnull)text OBJC_DESIGNATED_INITIALIZER;
- (void)setTextWithText:(NSString * _Nonnull)text;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setup;
- (void)didMoveToSuperview;
- (void)show;
- (void)hide;
- (nonnull instancetype)initWithEffect:(UIVisualEffect * _Nullable)effect SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC9Instamojo14UPIPaymentView")
@interface UPIPaymentView : UIViewController <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified alertMessageView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified vpaDetailsView;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified vpa;
@property (nonatomic, strong) Spinner * _Null_unspecified spinner;
@property (nonatomic) BOOL continueCheck;
- (void)viewDidLoad;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)verifyPaymentWithSender:(UIBarButtonItem * _Nonnull)sender;
- (void)checkForStatusTransaction;
- (void)onStatusCheckCompleteWithPaymentComplete:(BOOL)paymentComplete exception:(NSString * _Nonnull)exception;
- (void)onPaymentStatusComplete;
- (void)showAlertWithTitle:(NSString * _Nonnull)title errorMessage:(NSString * _Nonnull)errorMessage;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
